apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: webipie.dev
      http:
        paths:
          - path: /api/orders/?(.*)
            backend:
              serviceName: orders-srv
              servicePort: 3000   
          - path: /api/products/?(.*)
            backend:
              serviceName: products-srv
              servicePort: 3000           